[project]
name = "tmux-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "libtmux>=0.46.2",
    "pydantic-ai>=1.0.2",
    "pydantic-ai-slim[google,openai]>=1.0.2",
    "pyperclip>=1.9.0",
    "python-dotenv>=1.1.1",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pyinstaller>=6.15.0",
]
